import Head from 'next/head';
import { MainLayoult } from '../components/navBar/MainLayoult';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <MainLayoult>

      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="keyWords" content="next,javascript,react" />
          <meta name="description" content="Generated by create next app" />
          <meta charSet="utf-8" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>hello</h1>

      </div>
    </MainLayoult>
  )
};
